[source]
stage_type = "astrocap_source_gstreamer::GstSource"
file_path = "tests/processed_crop_2_lossless.mkv"

[[stages]]
stage_type = "astrocap_processor_point_detector::PointDetectorProcessor"
algorithm = "LocalMaxima"
centroid_window = 3
min_separation = 10
point_threshold = 80

[[stages]]
stage_type = "astrocap_processor_detection_export::DetectionExportProcessor"
output_path = "tests/processed_crop_2_detetions.json"

[sink]
stage_type = "vyd::DummySink"
