[source]
stage_type = "astrocap_source_recorded_detections::RecordedDetectionsSource"
input_path = "tests/processed_crop_1_detections.json"

[[stages]]
stage_type = "astrocap_processor_tracker::TrackerProcessor"
tracker_strategy = "MultiHypothesis"

[sink]
stage_type = "astrocap_sink_tracker_evaluator::TrackerEvaluatorSink"
annotations_file = "tests/processed_crop_1_lossless-annotations.json"
distance_threshold = 5.0
output_path = "tracker_evaluation_results_threshold.json"
