[source]
stage_type = "astrocap_source_gstreamer::GstSource"
file_path = "tests/test.mkv"
pseudo_live = false
# zc_enabled = false

[[stages]]
stage_type = "astrocap_processor_rerun_img_tee::RerunTeeProcessor"
tag = "original"

[[stages]]
stage_type = "astrocap_processor_median_sub::MedianProcessor"
async = true

[[stages]]
stage_type = "astrocap_processor_rerun_img_tee::RerunTeeProcessor"
key = "video/median"
tag = "median"

[[stages]]
stage_type = "astrocap_processor_mask::MaskProcessor"
file_path = "mask-2.png"

[[stages]]
stage_type = "astrocap_processor_median_sub::ImgSubberProcessor"
subtractand_key = "median"

[[stages]]
stage_type = "astrocap_processor_rerun_img_tee::RerunTeeProcessor"
tag = "median_subbed"

[[stages]]
stage_type = "astrocap_processor_frame_stacker::FrameStackerProcessor"
stack_depth = 8
renormalize = "Sqrt"

[[stages]]
stage_type = "astrocap_processor_point_detector::PointDetectorProcessor"
algorithm = "LocalMaxima"
centroid_window = 2
min_separation = 3
point_threshold = 60

[[stages]]
stage_type = "astrocap_processor_point_fitter::PointFitterProcessor"

[[stages]]
stage_type = "astrocap_processor_model::ModelState"
max_existing_candidate_match_dist = 4
disable_kalman_velocity = true

[sink]
stage_type = "astrocap_sink_rerun::RerunSink"
