[workspace]
members = [
    #    "astrocap_model",
    "gst_rtsp_client",
    #    "opencv_load_from_file",
    #    "read_mkv_metadata",
    "astrocap_annotator",
    "astrocap_core",
    "astrocap_processor_frame_stacker",
    "astrocap_processor_mask",
    "astrocap_processor_median_sub",
    "astrocap_processor_model",
    "astrocap_processor_point_detector",
    "astrocap_processor_detection_export",
    "astrocap_processor_point_fitter",
    "astrocap_processor_video_export",
    "astrocap_processor_rerun_img_tee",
    "astrocap_processor_tracker",
    "astrocap_sink_point_detector_evaluator",
    "astrocap_sink_tracker_evaluator",
    "astrocap_sink_rerun",
    "astrocap_source_gstreamer",
    "astrocap_source_gstreamer_gpu",
    "astrocap_source_recorded_detections",
    "astrocap_main",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
authors = ["Scott Donnelly"]
description = "Astronomical video processing suite"
documentation = "https://astrocap.dev/docs"

[profile.release]
debug = true


[workspace.dependencies]
astrocap_core = { path = "./astrocap_core" }
astrocap_processor_frame_stacker = { path = "./astrocap_processor_frame_stacker" }
astrocap_processor_mask = { path = "./astrocap_processor_mask" }
astrocap_processor_median_sub = { path = "./astrocap_processor_median_sub" }
astrocap_processor_model = { path = "./astrocap_processor_model" }
astrocap_processor_point_detector = { path = "./astrocap_processor_point_detector" }
astrocap_processor_detection_export = { path = "./astrocap_processor_detection_export" }
astrocap_processor_point_fitter = { path = "./astrocap_processor_point_fitter" }
astrocap_processor_video_export = { path = "astrocap_processor_video_export" }
astrocap_processor_rerun_img_tee = { path = "./astrocap_processor_rerun_img_tee" }
astrocap_processor_tracker = { path = "./astrocap_processor_tracker" }
astrocap_sink_point_detector_evaluator = { path = "astrocap_sink_point_detector_evaluator" }
astrocap_sink_rerun = { path = "astrocap_sink_rerun" }
astrocap_sink_tracker_evaluator = { path = "astrocap_sink_tracker_evaluator" }
astrocap_source_gstreamer = { path = "./astrocap_source_gstreamer" }
astrocap_source_recorded_detections = { path = "./astrocap_source_recorded_detections" }

anyhow = "1"
az = "1"
bytes = "1"
chrono = { version = "0.4.40", features = ["serde"] }
clap = { version = "4.0", features = ["derive"] }
http = "1"
image = { version = "0.24", default-features = false, features = ["png", "jpeg"] }
imageproc = { version = "0.23" }
metrics = "0.24"
nalgebra = "0.32"
once_cell = "1"
rerun = { version = "0.23", features = ["run", "server"], default-features = false }
serde = { version = "1", features = ["derive"] }
tracing = "0.1"
thiserror = "2"
toml = { version = "0.9", features = ["serde"] }
kiddo = { version = "5" }
serde_json = "1"
