[package]
name = "astrocap_sink_rerun"
edition = "2024"
version.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true

[dependencies]
vyd = { workspace = true }
astrocap_core = { path = "../astrocap_core" }
rerun = { workspace = true }
toml = "0.9.5"
tracing = "0.1.41"


[lib]
name = "astrocap_sink_rerun"