[package]
name = "astrocap_main"
edition = "2024"
version.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true

[dependencies]
vyd = { workspace = true }
astrocap_core = { workspace = true }
astrocap_processor_detection_export = { workspace = true }
astrocap_processor_frame_stacker = { workspace = true }
astrocap_processor_point_detector = { workspace = true }
astrocap_processor_point_fitter = { workspace = true }
astrocap_processor_mask = { workspace = true }
astrocap_processor_median_sub = { workspace = true }
#astrocap_processor_model = { workspace = true }
astrocap_processor_rerun_img_tee = { workspace = true }
astrocap_processor_solvastro = { workspace = true }
astrocap_processor_tracker = { workspace = true }
astrocap_processor_video_export = { workspace = true }
astrocap_sink_point_detector_evaluator = { workspace = true }
astrocap_sink_rerun = { workspace = true }
astrocap_sink_tracker_evaluator = { workspace = true }
astrocap_source_gstreamer = { workspace = true }
astrocap_source_recorded_detections = { workspace = true }

clap = { workspace = true }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
ctrlc = "3.4.7"
