[package]
name = "astrocap_model"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
argmin = "0.8"
argmin-math = { version = "0.3", features = ["ndarray_latest-serde", "nalgebra_latest-serde"] }
az = "1"
derive_more = "0.99.17"
itertools = "0.12"
kiddo = { version = "6.3" }
lazy_static = "1"
nalgebra = "0.32"
ndarray = "0.15"
nonmax = { version = "0.5", features = ["serde"] }
num-traits = "0.2"
ordered-float = "4"
rerun = { workspace = true }
rusttype = "0.9"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
#solvastro = { path = "../../solvastro" }
tracing = "0.1"

[dev-dependencies]
imageproc = "0.23"
image = { version = "0.24", default-features = false, features = ["png", "jpeg"] }

[lib]
name = "astrocap_model"
