[package]
name = "astrocap_processor_rerun_img_tee"
edition = "2024"
version.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true

[dependencies]
vyd = { workspace = true }
astrocap_core = { path = "../astrocap_core" }
rerun = { workspace = true }
toml = { workspace = true }
tracing = { workspace = true }

[lib]
name = "astrocap_processor_rerun_img_tee"