[package]
name = "astrocap_processor_point_detector"
version = "0.1.0"
edition = "2021"

[dependencies]
vyd = { workspace = true }
astrocap_core = { path = "../astrocap_core" }
astrocap_source_gstreamer = { path = "../astrocap_source_gstreamer" }
anyhow = "1.0"
clap = { version = "4.0", features = ["derive"] }
image = { workspace = true }
imageproc = { workspace = true }
nalgebra = { workspace = true }
ordered-float = "5"
rerun = { workspace = true }
serde = { version = "1", features = ["derive"] }
toml = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[dev-dependencies]
kiddo = { workspace = true }
serde_json = { workspace = true }

[lib]
name = "astrocap_processor_point_detector"
